### ISSUE TITLE
This plugin only checks for line endings?

### ISSUE THREAD

**Issue by jizusun** [SAP/eslint-plugin-openui5#5]
I'm wondering in which real case I can use this plugin ...

Actually I want to find how to support rules like: 
```
"sap-no-localstorage": 2,
"sap-no-ui5base-prop": 2,
"sap-no-dom-access": 1,
```
etc., which I've found in SAP WebIDE generated ``.eslint`` file.

I would really appreciate it if you can give me some hints about this, thanks.

**Comment by matz3** [comment]
Actually right now there isn't really a use case for this plugin. The line-endings check is part of ESLint since quite a while (see #4).

The rules you've mentioned seem to be part of the ["Fiori JavaScript Validator Rules" within the SAP WebIDE](https://help.hana.ondemand.com/webide/frameset.htm?233396e994584fe9b4c7ab6cb2798640.html).
